from django.db import models
from UserServices.models import Users
from InventoryServices.models import Warehouse
from ProductServices.models import Products

class PurchaseOrder(models.Model):
    id = models.AutoField(primary_key=True)
    warehouse_id = models.ForeignKey(Warehouse, on_delete=models.CASCADE, blank=True, null=True, related_name=' warehouse_id')
    supplier_id = models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='supplier_id')
    last_updated_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='last_updated_by_user_id')
    po_code = models.CharField(max_length=255)
    po_date = models.DateTimeField()
    excepted_delivery_date = models.DateTimeField()
    payment_terms = models.CharField(max_length=255, choices=[('CASH','CASH'),('CREDIT','CREDIT'),('ONLINE','ONLINE'),('CHEQUE','CHEQUE') ],default='CASH')
    payment_status = models.CharField(max_length=255, choices=[('PAID','PAID'),('UNPAID','UNPAID'),('PARTIAL PAID','PARTIAL PAID'),('CANCELLED','CANCELLED')],default='UNPAID')
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2)
    due_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_type = models.CharField(max_length=255, choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT')], default='PERCENTAGE')
    shipping_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_type = models.CharField(max_length=255, choices=[('FREE','FREE'),('PAID','PAID')], default='FREE')
    shipping_tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    additional_details = models.JSONField()
    status = models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('RECEIVED','RECEIVED'),('PARTIAL RECEIVED','PARTIAL RECEIVED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED'),('PARTIAL DELIVERED','PARTIAL DELIVERED')], default='DRAFT')
    create_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='create_by_user_id')
    domain_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='domain_user_id')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    approve_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='approve_by_user_id')
    approve_at = models.DateTimeField()
    cancelled_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='cancelled_by_user_id')
    cancelled_at = models.DateTimeField()
    cancelled_reason = models.TextField()
    received_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='received_by_user_id')
    received_at = models.DateTimeField()
    returned_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='returned_by_user_id')
    returned_at = models.DateTimeField()

class PurchaseOrderItems(models.Model):
    id = models.AutoField(primary_key=True)
    po_id = models.ForeignKey(Warehouse, on_delete=models.CASCADE, blank=True, null=True, related_name='po_id')
    product_id = models.ForeignKey(Warehouse, on_delete=models.CASCADE, blank=True, null=True, related_name='product_id')
    quantity_ordered = models.IntegerField()
    quantity_received = models.IntegerField()
    quantity_cancelled = models.IntegerField()
    quantity_returned = models.IntegerField()
    buying_price = models.DecimalField(max_digits=10, decimal_places=2)
    selling_price = models.DecimalField(max_digits=10, decimal_places=2)  
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    amount_returned = models.DecimalField(max_digits=10, decimal_places=2)
    amount_cancelled =models.DecimalField(max_digits=10, decimal_places=2)
    amount_ordered = models.DecimalField(max_digits=10, decimal_places=2)
    tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_type = models.CharField(max_length=255, choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT')], default='PERCENTAGE')
    additional_details = models.JSONField()
    status = models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('RECEIVED','RECEIVED'),('PARTIAL RECEIVED','PARTIAL RECEIVED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED')], default='DRAFT')
    create_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='create_by_user_id')
    updated_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='updated_by_user_id')
    domain_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='domain_user_id')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    approve_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='approve_by_user_id')
    approve_at = models.DateTimeField()
    cancelled_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='cancelled_by_user_id')
    cancelled_at = models.DateTimeField()
    cancelled_reason = models.TextField()
    received_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='received_by_user_id')
    received_at = models.DateTimeField()
    returned_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='returned_by_user_id')
    returned_at = models.DateTimeField()

class PurchaseOrderInWardedLog(models.Model):
    id = models.AutoField(primary_key=True)
    po_id = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='po_item_id')
    invoice_path = models.TextField()
    invoice_number = models.CharField()
    notes = models.CharField()
    inwarded_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='inwarded_by_user_id')
    inwarded_at = models.DateTimeField()
    status = models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('RECEIVED','RECEIVED'),('PARTIAL RECEIVED','PARTIAL RECEIVED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED')], default='DRAFT')
    additional_details = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class PurchaseOrderItemInWardedLog(models.Model):
    id = models.AutoField(primary_key=True)
    po_item_id = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='po_item_id')
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_type = models.CharField(max_length=255, choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT')], default='PERCENTAGE')
    shipping_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    domain_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='domain_user_id')
    status = models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('RECEIVED','RECEIVED'),('PARTIAL RECEIVED','PARTIAL RECEIVED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED')], default='DRAFT')
    additional_details = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class PurchaseOrderLogs(models.Model):
    id = models.AutoField(primary_key=True)
    po_id = models.ForeignKey(PurchaseOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='po_item_id')
    comment = models.TextField()
    create_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='create_by_user_id')
    domain_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='domain_user_id')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class SalesOrder(models.Model):
    id = models.AutoField(primary_key=True)
    customer_id = models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='supplier_id')
    last_updated_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='last_updated_by_user_id')
    so_code = models.CharField(max_length=255)
    so_date = models.DateTimeField()
    excepted_delivery_date = models.DateTimeField()
    payment_terms = models.CharField(max_length=255, choices=[('CASH','CASH'),('CREDIT','CREDIT'),('ONLINE','ONLINE'),('CHEQUE','CHEQUE') ],default='CASH')
    payment_status = models.CharField(max_length=255, choices=[('PAID','PAID'),('UNPAID','UNPAID'),('PARTIAL PAID','PARTIAL PAID'),('CANCELLED','CANCELLED')],default='UNPAID')
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    paid_amount = models.DecimalField(max_digits=10, decimal_places=2)
    due_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_type = models.CharField(max_length=255, choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT')], default='PERCENTAGE')
    shipping_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_type = models.CharField(max_length=255, choices=[('FREE','FREE'),('PAID','PAID')], default='FREE')
    shipping_tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    additional_details = models.JSONField()
    status = models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('DELIVERED','DELIVERED'),('PARTIAL DELIVERED','PARTIAL DELIVERED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED')], default='DRAFT')
    create_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='create_by_user_id')
    domain_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='domain_user_id')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    approve_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='approve_by_user_id')
    approve_at = models.DateTimeField()
    cancelled_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='cancelled_by_user_id')
    cancelled_at = models.DateTimeField()
    cancelled_reason = models.TextField()
    received_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='received_by_user_id')
    received_at = models.DateTimeField()
    returned_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='returned_by_user_id')
    returned_at = models.DateTimeField()

class SalesOrderOrderItems(models.Model):
    id = models.AutoField(primary_key=True)
    so_id = models.ForeignKey(SalesOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='so_id')
    product_id = models.ForeignKey(Warehouse, on_delete=models.CASCADE, blank=True, null=True, related_name='product_id_so')
    quantity_ordered = models.IntegerField()
    quantity_delivered = models.IntegerField()
    quantity_shipped = models.IntegerField()
    quantity_cancelled = models.IntegerField()
    quantity_returned = models.IntegerField()
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)  
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    amount_returned = models.DecimalField(max_digits=10, decimal_places=2)
    amount_cancelled =models.DecimalField(max_digits=10, decimal_places=2)
    amount_ordered = models.DecimalField(max_digits=10, decimal_places=2)
    tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_cancelled_tax_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_type = models.CharField(max_length=255, choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT')], default='PERCENTAGE')
    additional_details = models.JSONField()
    status = models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('DELIVERED','DELIVERED'),('PARTIAL DELIVERED','PARTIAL DELIVERED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED'),('PARTIAL DELIVERED','PARTIAL DELIVERED')], default='DRAFT')
    create_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='create_by_user_id')
    updated_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE, blank=True, null=True, related_name='updated_by_user_id')
    domain_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='domain_user_id')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    approve_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='approve_by_user_id')
    approve_at = models.DateTimeField()
    cancelled_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='cancelled_by_user_id')
    cancelled_at = models.DateTimeField()
    cancelled_reason = models.TextField()
    received_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='received_by_user_id')
    received_at = models.DateTimeField()
    returned_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='returned_by_user_id')
    returned_at = models.DateTimeField()

class SalesOrderOutWardedLog(models.Model):
    id = models.AutoField(primary_key=True)
    so_id = models.ForeignKey(SalesOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='so_order_id')
    invoice_path = models.TextField()
    invoice_number = models.CharField(max_length=255)
    notes = models.CharField()
    outwarded_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='inwarded_by_user_id')
    outwarded_at = models.DateTimeField()
    status = models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('DELIVERED','DELIVERED'),('PARTIAL DELIVERED','PARTIAL DELIVERED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED'),('PARTIAL DELIVERED','PARTIAL DELIVERED')], default='DRAFT')
    additional_details = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class SalesOrderItemOutWardedLog(models.Model):
    id = models.AutoField(primary_key=True)
    so_item_id = models.ForeignKey(SalesOrderOrderItems, on_delete=models.CASCADE, blank=True, null=True, related_name='so_item_id')
    outwarded_quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2)
    discount_type = models.CharField(max_length=255, choices=[('PERCENTAGE','PERCENTAGE'),('AMOUNT','AMOUNT')], default='PERCENTAGE')
    shipping_amount = models.DecimalField(max_digits=10, decimal_places=2)
    shipping_tax_percentage = models.DecimalField(max_digits=10, decimal_places=2)
    domain_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='domain_user_id')
    status = models.CharField(max_length=255, choices=[('DRAFT','DRAFT'),('SENT','SENT'),('DELIVERED','DELIVERED'),('PARTIAL DELIVERED','PARTIAL DELIVERED'),('CANCELLED','CANCELLED'),('RETURNED','RETURNED')], default='DRAFT')
    additional_details = models.JSONField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class SalesOrderLogs(models.Model):
    id = models.AutoField(primary_key=True)
    so_id = models.ForeignKey(SalesOrder, on_delete=models.CASCADE, blank=True, null=True, related_name='so_item_id')
    comment = models.TextField()
    create_by_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='create_by_user_id')
    domain_user_id = models.ForeignKey(Users, on_delete=models.CASCADE,  blank=True, null=True, related_name='domain_user_id')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)