# Generated by Django 5.1.5 on 2025-02-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
