# Generated by Django 5.1.5 on 2025-02-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0003_alter_users_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_pic',
        ),
    ]
