# Generated by Django 5.1.6 on 2025-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserServices', '0005_users_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('User', 'User'), ('Supplier', 'Supplier'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Super Admin', 'Super Admin')], max_length=50, null=True),
        ),
    ]
