# Generated by Django 5.1.5 on 2025-02-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.IntegerField()),
                ('mrp', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_type', models.CharField(choices=[('AMOUNT', 'AMOUNT'), ('PERCENTAGE', 'PERCENTAGE')], default='AMOUNT', max_length=255)),
                ('discount_amount', models.FloatField()),
                ('sr_no', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('mfg_date', models.DateTimeField(blank=True, null=True)),
                ('uom', models.FloatField(verbose_name=255)),
                ('ptr', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('quality_inwarded', models.IntegerField()),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'IN_STOCK'), ('OUT_OF_STOCK', 'OUT_OF_STOCK'), ('DAMAGED', 'DAMAGED'), ('LOST', 'LOST')], default='IN_STOCK', max_length=255)),
                ('inward_type', models.CharField(choices=[('PURCHASE', 'PURCHASE'), ('RETURN', 'RETURN'), ('REPLACEMENT', 'REPLACEMENT'), ('WAREHOUSE TRANFER', 'WAREHOUSE TRANFER')], default='PURCHASE', max_length=255)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.IntegerField()),
                ('status', models.CharField(choices=[('INWARD', 'INWARD'), ('OUTWARD', 'OUTWARD'), ('DAMAGED', 'DAMAGED'), ('LOST', 'LOST'), ('EXPIRED', 'EXPIRED'), ('RETURNED', 'RETURNED'), ('ADJUSTMENT', 'ADJUSTMENT'), ('WAREHOUSE TRANFER', 'WAREHOUSE TRANFER')], default='INWARD', max_length=255)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RackAndShelvesAndFloor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rack', models.CharField(blank=True, max_length=255, null=True)),
                ('shelf', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=255)),
                ('size', models.CharField(choices=[('SMALL', 'SMALL'), ('MEDIUM', 'MEDIUM'), ('LARGE', 'LARGE')], default='SMALL', max_length=255)),
                ('capacity', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], default='LOW', max_length=255)),
                ('warehouse_type', models.CharField(choices=[('OWNED', 'OWNED'), ('LEASED', 'LEASED')], default='OWNED', max_length=255)),
                ('additional_details', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
